version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    ports:
      - 9100:9100
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress  
    volumes:
      - ./node_exporter-1.5.0.linux-amd64.tar.gz:/root/node_exporter-1.5.0.linux-amd64.tar.gz
    working_dir: /root
    command: >
      bash -c "service apache2 start &&
      tar xvfz node_exporter-1.5.0.linux-amd64.tar.gz &&
      cd node_exporter-1.5.0.linux-amd64 &&
      ./node_exporter"
      
volumes:
    db_data: