version: 0.2
env:
  secrets-manager:
    DOCKER_USERID: arn:aws:secretsmanager:ap-northeast-1:429535751272:secret:dockerLogin-r9WdIT:DOCKER_USERID
    DOCKER_PASSWD: arn:aws:secretsmanager:ap-northeast-1:429535751272:secret:dockerLogin-r9WdIT:DOCKER_PASSWD

phases:
  pre_build:
    commands:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - echo $DOCKER_PASSWD | docker login -u $DOCKER_USERID --password-stdin
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 429535751272.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=429535751272.dkr.ecr.ap-northeast-1.amazonaws.com/certdbfunction
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:         
      - docker build -t $REPOSITORY_URI:latest ./back-src
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
    files: imageDetail.json