global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#alerts'