version: '3'

services:
  splunk:
    image: splunk/splunk:latest
    ports:
      - 10000:8000
    restart: always
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: mypassword
    networks:
      - webnet

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    networks:
      - webnet
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress  

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - webnet

networks:
  webnet: