global:
  slack_api_url: 'https://hooks.slack.com/services/自分のslackToken値'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#alerts'