global:
  scrape_interval: 15s 

scrape_configs:

  - job_name: 'webapp'
    static_configs:
      - targets:
        - 'wordpress:9100'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9090'
          
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093

rule_files:
  - /etc/prometheus/rules.yml