apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      run: nginx-balancer
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-balancer
    spec:
      containers:
        - name: nginx-dep
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP